export const projects = [
  {
    id: 1,
    title: 'Halcyon Theme',
    description: 'A minimal, dark blue theme for VS Code, Sublime Text, Atom, iTerm, and more. Available on Visual Studio Marketplace, Package Control, Atom Package Manager, and npm.',
    tech: ['VS Code', 'Design'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project1/800/500',
    featured: true,
  },
  {
    id: 2,
    title: 'Spotify Profile',
    description: 'A web app for visualizing personalized Spotify data. View your top artists, top tracks, recently played tracks, and detailed audio information about each track.',
    tech: ['React', 'Express', 'Spotify API'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project2/800/500',
    featured: true,
  },
  {
    id: 3,
    title: 'Build a Spotify Connected App',
    description: 'Video course that teaches how to build a web app with the Spotify Web API. Topics covered include the principles of REST APIs, user auth flows, Node, Express, React, Styled Components, and more.',
    tech: ['React', 'Node.js', 'Express'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project3/800/500',
    featured: true,
  },
  {
    id: 4,
    title: 'E-Commerce Platform',
    description: 'A full-stack e-commerce solution with user authentication, payment processing, and an admin dashboard.',
    tech: ['Next.js', 'TypeScript', 'Stripe'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project4/800/500',
    featured: false,
  },
  {
    id: 5,
    title: 'Task Management App',
    description: 'A drag-and-drop task management tool inspired by Trello, built with modern web technologies.',
    tech: ['React', 'TypeScript', 'Tailwind CSS'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project5/800/500',
    featured: false,
  },
  {
    id: 6,
    title: 'Weather Dashboard',
    description: 'Real-time weather dashboard using the OpenWeather API with location tracking and 7-day forecasts.',
    tech: ['JavaScript', 'API', 'CSS'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project6/800/500',
    featured: false,
  },
  {
    id: 7,
    title: 'AI Chat Interface',
    description: 'A responsive chat interface for interacting with LLMs, featuring markdown support and code highlighting.',
    tech: ['React', 'Next.js', 'Tailwind CSS'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project7/800/500',
    featured: false,
  },
  {
    id: 8,
    title: 'Personal Blog',
    description: 'A static blog generated with Next.js and MDX, featuring a dark mode toggle and reading time estimates.',
    tech: ['Next.js', 'MDX', 'Design'],
    github: 'https://github.com',
    external: 'https://example.com',
    image: 'https://picsum.photos/seed/project8/800/500',
    featured: false,
  }
];
